/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const DataTableLazyImport = createFileRoute('/data-table')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DataTableLazyRoute = DataTableLazyImport.update({
  path: '/data-table',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/data-table.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/data-table': {
      preLoaderRoute: typeof DataTableLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DataTableLazyRoute,
])

/* prettier-ignore-end */
